### ISSUE TITLE
Cannot use setRecoil()

### ISSUE THREAD

**Issue by vatana7** [luisanton-io/recoil-nexus#27]
I couldn't update recoil state. It shows this error

Uncaught TypeError: nexus.set is not a function
    at setRecoil (RecoilNexus.tsx:46:1)
    at updateResumeObject (index.js:8:1)
    at onClick (index.js:42:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates$1 (react-dom.development.js:22396:1)
    at batchedEventUpdates (react-dom.development.js:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)

**Comment by bonesoul** [comment]
@vatana7 having the same issue, what was the solution for you?

**Comment by luisanton-io** [comment]
Possibly like #20

**Comment by vatana7** [comment]
@bonesoul please check #20 like @luisanton-io said
